#!/bin/sh
if [ -n "$1" ]; then javac -classpath ../RXTXcomm.jar bravo/*/*.java; fi
java -classpath ".:../RXTXcomm.jar" -Djava.library.path=.. bravo.game.Draughts
# give pathing access to board state
# send path for captures
# make AI wait for human in case of error
